export const metadata = {
  title: 'Next pizza',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en">{children}</html>
}
